[phases.setup]
nixPkgs = ["...", "chromium", "ffmpeg"]

[phases.build]
cmds = ["npm install", "npm run build"]

[start]
cmd = "npm run start:prod"

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"
