services:
  - type: web
    name: zelar-ia
    env: docker
    plan: free
    branch: main
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome-stable
      - key: NODE_ENV
        value: production